2014-10-18 22:06:08 Error: [MissingComponentException] Component class ToolbarComponent could not be found.
Exception Attributes: array (
  'class' => 'ToolbarComponent',
  'plugin' => 'DebugKit',
)
Request URL: /logistics/
Stack Trace:
#0 /var/www/html/logistics/lib/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('DebugKit.Toolba...', Array)
#1 /var/www/html/logistics/lib/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(PagesController))
#2 /var/www/html/logistics/lib/Cake/Routing/Dispatcher.php(186): Controller->constructClasses()
#3 /var/www/html/logistics/lib/Cake/Routing/Dispatcher.php(165): Dispatcher->_invoke(Object(PagesController), Object(CakeRequest))
#4 /var/www/html/logistics/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 /var/www/html/logistics/index.php(41): require('/var/www/html/l...')
#6 {main}
2014-10-26 09:50:06 Error: [MissingComponentException] Component class ToolbarComponent could not be found.
Exception Attributes: array (
  'class' => 'ToolbarComponent',
  'plugin' => 'DebugKit',
)
Request URL: /logistics/
Stack Trace:
#0 /var/www/html/logistics/lib/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('DebugKit.Toolba...', Array)
#1 /var/www/html/logistics/lib/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(PagesController))
#2 /var/www/html/logistics/lib/Cake/Routing/Dispatcher.php(186): Controller->constructClasses()
#3 /var/www/html/logistics/lib/Cake/Routing/Dispatcher.php(165): Dispatcher->_invoke(Object(PagesController), Object(CakeRequest))
#4 /var/www/html/logistics/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 /var/www/html/logistics/index.php(41): require('/var/www/html/l...')
#6 {main}
2014-10-26 06:17:00 Error: [MissingComponentException] Component class ToolbarComponent could not be found.
Exception Attributes: array (
  'class' => 'ToolbarComponent',
  'plugin' => 'DebugKit',
)
Request URL: /logistics/
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Controller\ComponentCollection.php(53): ComponentCollection->load('DebugKit.Toolba...', Array)
#1 E:\xampp\htdocs\logistics\lib\Cake\Controller\Controller.php(643): ComponentCollection->init(Object(PagesController))
#2 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(186): Controller->constructClasses()
#3 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(PagesController), Object(CakeRequest))
#4 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 E:\xampp\htdocs\logistics\index.php(41): require('E:\xampp\htdocs...')
#6 {main}
2014-10-26 09:53:40 Error: [MissingComponentException] Component class ToolbarComponent could not be found.
Exception Attributes: array (
  'class' => 'ToolbarComponent',
  'plugin' => 'DebugKit',
)
Request URL: /logistics/
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Controller\ComponentCollection.php(53): ComponentCollection->load('DebugKit.Toolba...', Array)
#1 E:\xampp\htdocs\logistics\lib\Cake\Controller\Controller.php(643): ComponentCollection->init(Object(PagesController))
#2 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(186): Controller->constructClasses()
#3 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(PagesController), Object(CakeRequest))
#4 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 E:\xampp\htdocs\logistics\index.php(41): require('E:\xampp\htdocs...')
#6 {main}
2014-10-26 11:07:14 Error: [MissingControllerException] Controller class PostsController could not be found.
Exception Attributes: array (
  'class' => 'PostsController',
  'plugin' => NULL,
)
Request URL: /logistics/posts
Stack Trace:
#0 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-10-26 11:09:22 Error: [MissingControllerException] Controller class PostsController could not be found.
Exception Attributes: array (
  'class' => 'PostsController',
  'plugin' => NULL,
)
Request URL: /logistics/posts
Stack Trace:
#0 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-10-26 11:10:57 Error: [MissingControllerException] Controller class PostsController could not be found.
Exception Attributes: array (
  'class' => 'PostsController',
  'plugin' => NULL,
)
Request URL: /logistics/posts/index
Stack Trace:
#0 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-10-26 11:12:55 Error: [MissingControllerException] Controller class PostController could not be found.
Exception Attributes: array (
  'class' => 'PostController',
  'plugin' => NULL,
)
Request URL: /logistics/post/index
Stack Trace:
#0 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-10-26 11:13:35 Error: [MissingControllerException] Controller class PostController could not be found.
Exception Attributes: array (
  'class' => 'PostController',
  'plugin' => NULL,
)
Request URL: /logistics/post/index
Stack Trace:
#0 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-10-26 11:13:42 Error: Fatal Error (1): Class 'AppMOdel' not found in [E:\xampp\htdocs\logistics\app\Model\Post.php, line 2]
2014-10-26 11:13:42 Error: [FatalErrorException] Class 'AppMOdel' not found
Request URL: /logistics/posts/index
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Class 'AppMOdel...', 'E:\xampp\htdocs...', 2)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'AppMOdel...', 'E:\xampp\htdocs...', 2, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Class 'AppMOdel...', 'E:\xampp\htdocs...', 2, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-10-26 11:15:29 Error: [MissingActionException] Action PostsController::view() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'view',
)
Request URL: /logistics/posts/view/1
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#2 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-11-01 12:34:13 Error: [MissingControllerException] Controller class IndexController could not be found.
Exception Attributes: array (
  'class' => 'IndexController',
  'plugin' => NULL,
)
Request URL: /logistics/index
Stack Trace:
#0 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-11-01 12:46:23 Error: [MissingActionException] Action PostsController::view() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'view',
)
Request URL: /logistics/posts/view/1
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#2 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-11-01 12:47:04 Error: [MissingViewException] View file "E:\xampp\htdocs\logistics\app\View\Posts\view.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\xampp\\htdocs\\logistics\\app\\View\\Posts\\view.ctp',
)
Request URL: /logistics/posts/view/1
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\xampp\htdocs\logistics\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#4 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-11-01 12:47:08 Error: [MissingViewException] View file "E:\xampp\htdocs\logistics\app\View\Posts\view.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\xampp\\htdocs\\logistics\\app\\View\\Posts\\view.ctp',
)
Request URL: /logistics/posts/view/1
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\xampp\htdocs\logistics\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#4 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-11-01 12:49:56 Error: [MissingViewException] View file "E:\xampp\htdocs\logistics\app\View\Posts\view.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\xampp\\htdocs\\logistics\\app\\View\\Posts\\view.ctp',
)
Request URL: /logistics/posts/view/1
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\xampp\htdocs\logistics\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#4 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-11-01 13:18:25 Error: Fatal Error (1): Call to a member function create() on a non-object in [E:\xampp\htdocs\logistics\app\View\Posts\add.ctp, line 3]
2014-11-01 13:18:25 Error: [FatalErrorException] Call to a member function create() on a non-object
Request URL: /logistics/posts/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 3)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 3, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\xampp\htdocs...', 3, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-01 13:19:24 Error: Fatal Error (1): Call to a member function create() on a non-object in [E:\xampp\htdocs\logistics\app\View\Posts\add.ctp, line 3]
2014-11-01 13:19:24 Error: [FatalErrorException] Call to a member function create() on a non-object
Request URL: /logistics/posts/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 3)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 3, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\xampp\htdocs...', 3, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-01 13:21:19 Error: [MissingControllerException] Controller class PostController could not be found.
Exception Attributes: array (
  'class' => 'PostController',
  'plugin' => NULL,
)
Request URL: /logistics/post/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-11-01 13:21:32 Error: Fatal Error (1): Call to a member function create() on a non-object in [E:\xampp\htdocs\logistics\app\View\Posts\add.ctp, line 3]
2014-11-01 13:21:32 Error: [FatalErrorException] Call to a member function create() on a non-object
Request URL: /logistics/posts/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 3)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 3, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\xampp\htdocs...', 3, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-01 13:22:24 Error: Fatal Error (1): Call to a member function create() on a non-object in [E:\xampp\htdocs\logistics\app\View\Posts\add.ctp, line 3]
2014-11-01 13:22:24 Error: [FatalErrorException] Call to a member function create() on a non-object
Request URL: /logistics/posts/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 3)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 3, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\xampp\htdocs...', 3, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-01 13:22:25 Error: Fatal Error (1): Call to a member function create() on a non-object in [E:\xampp\htdocs\logistics\app\View\Posts\add.ctp, line 3]
2014-11-01 13:22:25 Error: [FatalErrorException] Call to a member function create() on a non-object
Request URL: /logistics/posts/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 3)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 3, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\xampp\htdocs...', 3, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-01 13:22:25 Error: Fatal Error (1): Call to a member function create() on a non-object in [E:\xampp\htdocs\logistics\app\View\Posts\add.ctp, line 3]
2014-11-01 13:22:25 Error: [FatalErrorException] Call to a member function create() on a non-object
Request URL: /logistics/posts/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 3)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 3, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\xampp\htdocs...', 3, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-01 13:22:26 Error: Fatal Error (1): Call to a member function create() on a non-object in [E:\xampp\htdocs\logistics\app\View\Posts\add.ctp, line 3]
2014-11-01 13:22:26 Error: [FatalErrorException] Call to a member function create() on a non-object
Request URL: /logistics/posts/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 3)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 3, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\xampp\htdocs...', 3, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-01 13:22:34 Error: Fatal Error (1): Call to a member function create() on a non-object in [E:\xampp\htdocs\logistics\app\View\Posts\add.ctp, line 5]
2014-11-01 13:22:34 Error: [FatalErrorException] Call to a member function create() on a non-object
Request URL: /logistics/posts/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 5)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 5, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\xampp\htdocs...', 5, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-01 13:22:35 Error: Fatal Error (1): Call to a member function create() on a non-object in [E:\xampp\htdocs\logistics\app\View\Posts\add.ctp, line 5]
2014-11-01 13:22:35 Error: [FatalErrorException] Call to a member function create() on a non-object
Request URL: /logistics/posts/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 5)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 5, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\xampp\htdocs...', 5, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-01 13:22:36 Error: Fatal Error (1): Call to a member function create() on a non-object in [E:\xampp\htdocs\logistics\app\View\Posts\add.ctp, line 5]
2014-11-01 13:22:36 Error: [FatalErrorException] Call to a member function create() on a non-object
Request URL: /logistics/posts/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 5)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 5, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\xampp\htdocs...', 5, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-01 13:23:24 Error: Fatal Error (1): Call to a member function create() on a non-object in [E:\xampp\htdocs\logistics\app\View\Posts\add.ctp, line 4]
2014-11-01 13:23:24 Error: [FatalErrorException] Call to a member function create() on a non-object
Request URL: /logistics/posts/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 4)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 4, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\xampp\htdocs...', 4, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-01 13:23:26 Error: Fatal Error (1): Call to a member function create() on a non-object in [E:\xampp\htdocs\logistics\app\View\Posts\add.ctp, line 4]
2014-11-01 13:23:26 Error: [FatalErrorException] Call to a member function create() on a non-object
Request URL: /logistics/posts/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 4)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 4, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\xampp\htdocs...', 4, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-01 13:26:29 Error: Fatal Error (1): Cannot access empty property in [E:\xampp\htdocs\logistics\lib\Cake\View\View.php, line 856]
2014-11-01 13:26:29 Error: [FatalErrorException] Cannot access empty property
Request URL: /logistics/posts/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Cannot access e...', 'E:\xampp\htdocs...', 856)
#1 [internal function]: ErrorHandler::handleError(1, 'Cannot access e...', 'E:\xampp\htdocs...', 856, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Cannot access e...', 'E:\xampp\htdocs...', 856, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-01 13:29:21 Error: Fatal Error (1): Cannot access empty property in [E:\xampp\htdocs\logistics\lib\Cake\View\View.php, line 856]
2014-11-01 13:29:21 Error: [FatalErrorException] Cannot access empty property
Request URL: /logistics/posts/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Cannot access e...', 'E:\xampp\htdocs...', 856)
#1 [internal function]: ErrorHandler::handleError(1, 'Cannot access e...', 'E:\xampp\htdocs...', 856, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Cannot access e...', 'E:\xampp\htdocs...', 856, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-01 13:36:33 Error: Fatal Error (1): Call to a member function setFlash() on a non-object in [E:\xampp\htdocs\logistics\app\Controller\PostsController.php, line 17]
2014-11-01 13:36:33 Error: [FatalErrorException] Call to a member function setFlash() on a non-object
Request URL: /logistics/posts/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 17, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\xampp\htdocs...', 17, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-01 13:37:28 Error: Fatal Error (1): Call to a member function setFlash() on a non-object in [E:\xampp\htdocs\logistics\app\Controller\PostsController.php, line 17]
2014-11-01 13:37:28 Error: [FatalErrorException] Call to a member function setFlash() on a non-object
Request URL: /logistics/posts/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 17, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\xampp\htdocs...', 17, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-01 13:37:32 Error: Fatal Error (1): Call to a member function setFlash() on a non-object in [E:\xampp\htdocs\logistics\app\Controller\PostsController.php, line 17]
2014-11-01 13:37:32 Error: [FatalErrorException] Call to a member function setFlash() on a non-object
Request URL: /logistics/posts/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 17, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\xampp\htdocs...', 17, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-01 14:05:51 Error: Fatal Error (1): Call to a member function setFlash() on a non-object in [E:\xampp\htdocs\logistics\app\Controller\PostsController.php, line 17]
2014-11-01 14:05:51 Error: [FatalErrorException] Call to a member function setFlash() on a non-object
Request URL: /logistics/posts/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 17, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\xampp\htdocs...', 17, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-01 14:07:02 Error: Fatal Error (1): Call to a member function setFlash() on a non-object in [E:\xampp\htdocs\logistics\app\Controller\PostsController.php, line 15]
2014-11-01 14:07:02 Error: [FatalErrorException] Call to a member function setFlash() on a non-object
Request URL: /logistics/posts/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 15)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 15, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\xampp\htdocs...', 15, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-01 14:07:11 Error: Fatal Error (1): Call to a member function setFlash() on a non-object in [E:\xampp\htdocs\logistics\app\Controller\PostsController.php, line 15]
2014-11-01 14:07:11 Error: [FatalErrorException] Call to a member function setFlash() on a non-object
Request URL: /logistics/posts/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 15)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 15, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\xampp\htdocs...', 15, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-01 14:11:56 Error: Fatal Error (1): Call to a member function setFlash() on a non-object in [E:\xampp\htdocs\logistics\app\Controller\PostsController.php, line 17]
2014-11-01 14:11:56 Error: [FatalErrorException] Call to a member function setFlash() on a non-object
Request URL: /logistics/posts/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 17, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\xampp\htdocs...', 17, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-01 14:12:07 Error: Fatal Error (1): Call to a member function setFlash() on a non-object in [E:\xampp\htdocs\logistics\app\Controller\PostsController.php, line 17]
2014-11-01 14:12:07 Error: [FatalErrorException] Call to a member function setFlash() on a non-object
Request URL: /logistics/posts/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 17, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\xampp\htdocs...', 17, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-18 16:51:12 Error: [MissingControllerException] Controller class IndexController could not be found.
Exception Attributes: array (
  'class' => 'IndexController',
  'plugin' => NULL,
)
Request URL: /logistics/index
Stack Trace:
#0 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-11-18 17:16:04 Error: [MissingActionException] Action PostsController::edit() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'edit',
)
Request URL: /logistics/posts/edit
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#2 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-11-18 17:16:07 Error: [MissingActionException] Action PostsController::edit() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'edit',
)
Request URL: /logistics/posts/edit/1
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#2 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-11-18 17:17:45 Error: [MissingControllerException] Controller class PostsindController could not be found.
Exception Attributes: array (
  'class' => 'PostsindController',
  'plugin' => NULL,
)
Request URL: /logistics/postsind
Stack Trace:
#0 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-11-18 17:17:50 Error: [MissingControllerException] Controller class IndexController could not be found.
Exception Attributes: array (
  'class' => 'IndexController',
  'plugin' => NULL,
)
Request URL: /logistics/index
Stack Trace:
#0 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-11-18 17:22:18 Error: [MissingActionException] Action PostsController::inddex() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'inddex',
)
Request URL: /logistics/posts/inddex/1
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#2 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-11-29 16:29:18 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /logistics/user
Stack Trace:
#0 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-11-29 16:29:24 Error: Fatal Error (1): Call to a member function allow() on a non-object in [E:\xampp\htdocs\logistics\app\Controller\UsersController.php, line 10]
2014-11-29 16:29:24 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /logistics/users
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 10, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\xampp\htdocs...', 10, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-29 16:37:00 Error: Fatal Error (4): syntax error, unexpected '(', expecting ')' in [E:\xampp\htdocs\logistics\app\Controller\AppController.php, line 38]
2014-11-29 16:37:00 Error: [FatalErrorException] syntax error, unexpected '(', expecting ')'
Request URL: /logistics/users
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 38)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 38, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\xampp\htdocs...', 38, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-29 16:37:15 Error: Fatal Error (4): syntax error, unexpected '(', expecting ')' in [E:\xampp\htdocs\logistics\app\Controller\AppController.php, line 38]
2014-11-29 16:37:15 Error: [FatalErrorException] syntax error, unexpected '(', expecting ')'
Request URL: /logistics/users
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 38)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 38, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\xampp\htdocs...', 38, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-29 16:37:16 Error: Fatal Error (4): syntax error, unexpected '(', expecting ')' in [E:\xampp\htdocs\logistics\app\Controller\AppController.php, line 38]
2014-11-29 16:37:16 Error: [FatalErrorException] syntax error, unexpected '(', expecting ')'
Request URL: /logistics/users
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 38)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 38, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\xampp\htdocs...', 38, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-29 16:37:16 Error: Fatal Error (4): syntax error, unexpected '(', expecting ')' in [E:\xampp\htdocs\logistics\app\Controller\AppController.php, line 38]
2014-11-29 16:37:16 Error: [FatalErrorException] syntax error, unexpected '(', expecting ')'
Request URL: /logistics/users
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 38)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 38, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\xampp\htdocs...', 38, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-29 16:37:16 Error: Fatal Error (4): syntax error, unexpected '(', expecting ')' in [E:\xampp\htdocs\logistics\app\Controller\AppController.php, line 38]
2014-11-29 16:37:16 Error: [FatalErrorException] syntax error, unexpected '(', expecting ')'
Request URL: /logistics/users
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 38)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 38, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\xampp\htdocs...', 38, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-29 16:37:41 Error: Fatal Error (4): syntax error, unexpected '(', expecting ')' in [E:\xampp\htdocs\logistics\app\Controller\AppController.php, line 38]
2014-11-29 16:37:41 Error: [FatalErrorException] syntax error, unexpected '(', expecting ')'
Request URL: /logistics/users
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 38)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 38, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\xampp\htdocs...', 38, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-29 16:37:42 Error: Fatal Error (4): syntax error, unexpected '(', expecting ')' in [E:\xampp\htdocs\logistics\app\Controller\AppController.php, line 38]
2014-11-29 16:37:42 Error: [FatalErrorException] syntax error, unexpected '(', expecting ')'
Request URL: /logistics/users
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 38)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 38, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\xampp\htdocs...', 38, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-29 16:37:42 Error: Fatal Error (4): syntax error, unexpected '(', expecting ')' in [E:\xampp\htdocs\logistics\app\Controller\AppController.php, line 38]
2014-11-29 16:37:42 Error: [FatalErrorException] syntax error, unexpected '(', expecting ')'
Request URL: /logistics/users
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 38)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 38, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\xampp\htdocs...', 38, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-29 16:37:42 Error: Fatal Error (4): syntax error, unexpected '(', expecting ')' in [E:\xampp\htdocs\logistics\app\Controller\AppController.php, line 38]
2014-11-29 16:37:42 Error: [FatalErrorException] syntax error, unexpected '(', expecting ')'
Request URL: /logistics/users
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 38)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 38, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\xampp\htdocs...', 38, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-29 16:37:42 Error: Fatal Error (4): syntax error, unexpected '(', expecting ')' in [E:\xampp\htdocs\logistics\app\Controller\AppController.php, line 38]
2014-11-29 16:37:42 Error: [FatalErrorException] syntax error, unexpected '(', expecting ')'
Request URL: /logistics/users
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 38)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 38, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\xampp\htdocs...', 38, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-29 16:37:43 Error: Fatal Error (4): syntax error, unexpected '(', expecting ')' in [E:\xampp\htdocs\logistics\app\Controller\AppController.php, line 38]
2014-11-29 16:37:43 Error: [FatalErrorException] syntax error, unexpected '(', expecting ')'
Request URL: /logistics/users
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 38)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 38, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\xampp\htdocs...', 38, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-29 16:39:17 Error: Fatal Error (4): syntax error, unexpected '(', expecting ')' in [E:\xampp\htdocs\logistics\app\Controller\AppController.php, line 38]
2014-11-29 16:39:17 Error: [FatalErrorException] syntax error, unexpected '(', expecting ')'
Request URL: /logistics/users
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 38)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 38, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\xampp\htdocs...', 38, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-29 16:42:43 Error: [MissingControllerException] Controller class BranchesController could not be found.
Exception Attributes: array (
  'class' => 'BranchesController',
  'plugin' => NULL,
)
Request URL: /logistics/branches
Stack Trace:
#0 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-11-29 16:43:17 Error: [MissingControllerException] Controller class BranchManagersController could not be found.
Exception Attributes: array (
  'class' => 'BranchManagersController',
  'plugin' => NULL,
)
Request URL: /logistics/branch_managers/login
Stack Trace:
#0 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-11-29 16:43:29 Error: [MissingControllerException] Controller class BranchManagersController could not be found.
Exception Attributes: array (
  'class' => 'BranchManagersController',
  'plugin' => NULL,
)
Request URL: /logistics/branch_managers/login
Stack Trace:
#0 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-11-29 16:46:28 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'invaliate' at line 1
Request URL: /logistics/users/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\xampp\htdocs\logistics\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('invaliate', Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('invaliate', Array, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Model\Datasource\DboSource.php(609): DboSource->fetchAll('invaliate', Array, Array)
#4 E:\xampp\htdocs\logistics\lib\Cake\Model\Model.php(808): DboSource->query('invaliate', Array, Object(User))
#5 E:\xampp\htdocs\logistics\app\Model\User.php(101): Model->__call('invaliate', Array)
#6 E:\xampp\htdocs\logistics\app\Model\User.php(101): User->invaliate('password_confir...', 'The passwords d...')
#7 [internal function]: User->matchPasswords(Array, Array)
#8 E:\xampp\htdocs\logistics\lib\Cake\Model\Validator\CakeValidationRule.php(275): call_user_func_array(Array, Array)
#9 E:\xampp\htdocs\logistics\lib\Cake\Model\Validator\CakeValidationSet.php(135): CakeValidationRule->process('password', Array, Array)
#10 E:\xampp\htdocs\logistics\lib\Cake\Model\ModelValidator.php(267): CakeValidationSet->validate(Array, false)
#11 E:\xampp\htdocs\logistics\lib\Cake\Model\ModelValidator.php(99): ModelValidator->errors(Array)
#12 E:\xampp\htdocs\logistics\lib\Cake\Model\Model.php(3367): ModelValidator->validates(Array)
#13 E:\xampp\htdocs\logistics\lib\Cake\Model\Model.php(1758): Model->validates(Array)
#14 E:\xampp\htdocs\logistics\app\Controller\UsersController.php(79): Model->save(Array)
#15 [internal function]: UsersController->add()
#16 E:\xampp\htdocs\logistics\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#17 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#18 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#19 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#20 {main}
2014-11-29 16:53:31 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'invaliate' at line 1
Request URL: /logistics/users/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\xampp\htdocs\logistics\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('invaliate', Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('invaliate', Array, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Model\Datasource\DboSource.php(609): DboSource->fetchAll('invaliate', Array, Array)
#4 E:\xampp\htdocs\logistics\lib\Cake\Model\Model.php(808): DboSource->query('invaliate', Array, Object(User))
#5 E:\xampp\htdocs\logistics\app\Model\User.php(101): Model->__call('invaliate', Array)
#6 E:\xampp\htdocs\logistics\app\Model\User.php(101): User->invaliate('password_confir...', 'The passwords d...')
#7 [internal function]: User->matchPasswords(Array, Array)
#8 E:\xampp\htdocs\logistics\lib\Cake\Model\Validator\CakeValidationRule.php(275): call_user_func_array(Array, Array)
#9 E:\xampp\htdocs\logistics\lib\Cake\Model\Validator\CakeValidationSet.php(135): CakeValidationRule->process('password', Array, Array)
#10 E:\xampp\htdocs\logistics\lib\Cake\Model\ModelValidator.php(267): CakeValidationSet->validate(Array, false)
#11 E:\xampp\htdocs\logistics\lib\Cake\Model\ModelValidator.php(99): ModelValidator->errors(Array)
#12 E:\xampp\htdocs\logistics\lib\Cake\Model\Model.php(3367): ModelValidator->validates(Array)
#13 E:\xampp\htdocs\logistics\lib\Cake\Model\Model.php(1758): Model->validates(Array)
#14 E:\xampp\htdocs\logistics\app\Controller\UsersController.php(79): Model->save(Array)
#15 [internal function]: UsersController->add()
#16 E:\xampp\htdocs\logistics\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#17 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#18 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#19 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#20 {main}
2014-11-29 17:05:37 Error: Fatal Error (4): syntax error, unexpected T_CONSTANT_ENCAPSED_STRING, expecting ')' in [E:\xampp\htdocs\logistics\app\Model\User.php, line 40]
2014-11-29 17:05:37 Error: [FatalErrorException] syntax error, unexpected T_CONSTANT_ENCAPSED_STRING, expecting ')'
Request URL: /logistics/users/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 40)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 40, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\xampp\htdocs...', 40, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-29 17:12:36 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'invaliate' at line 1
Request URL: /logistics/users/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\xampp\htdocs\logistics\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('invaliate', Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('invaliate', Array, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Model\Datasource\DboSource.php(609): DboSource->fetchAll('invaliate', Array, Array)
#4 E:\xampp\htdocs\logistics\lib\Cake\Model\Model.php(808): DboSource->query('invaliate', Array, Object(User))
#5 E:\xampp\htdocs\logistics\app\Model\User.php(90): Model->__call('invaliate', Array)
#6 E:\xampp\htdocs\logistics\app\Model\User.php(90): User->invaliate('password_confir...', 'The passwords d...')
#7 [internal function]: User->matchPasswords(Array, Array)
#8 E:\xampp\htdocs\logistics\lib\Cake\Model\Validator\CakeValidationRule.php(275): call_user_func_array(Array, Array)
#9 E:\xampp\htdocs\logistics\lib\Cake\Model\Validator\CakeValidationSet.php(135): CakeValidationRule->process('password', Array, Array)
#10 E:\xampp\htdocs\logistics\lib\Cake\Model\ModelValidator.php(267): CakeValidationSet->validate(Array, false)
#11 E:\xampp\htdocs\logistics\lib\Cake\Model\ModelValidator.php(99): ModelValidator->errors(Array)
#12 E:\xampp\htdocs\logistics\lib\Cake\Model\Model.php(3367): ModelValidator->validates(Array)
#13 E:\xampp\htdocs\logistics\lib\Cake\Model\Model.php(1758): Model->validates(Array)
#14 E:\xampp\htdocs\logistics\app\Controller\UsersController.php(79): Model->save(Array)
#15 [internal function]: UsersController->add()
#16 E:\xampp\htdocs\logistics\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#17 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#18 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#19 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#20 {main}
2014-11-29 17:12:53 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'invaliate' at line 1
Request URL: /logistics/users/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\xampp\htdocs\logistics\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('invaliate', Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('invaliate', Array, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Model\Datasource\DboSource.php(609): DboSource->fetchAll('invaliate', Array, Array)
#4 E:\xampp\htdocs\logistics\lib\Cake\Model\Model.php(808): DboSource->query('invaliate', Array, Object(User))
#5 E:\xampp\htdocs\logistics\app\Model\User.php(90): Model->__call('invaliate', Array)
#6 E:\xampp\htdocs\logistics\app\Model\User.php(90): User->invaliate('password_confir...', 'The passwords d...')
#7 [internal function]: User->matchPasswords(Array, Array)
#8 E:\xampp\htdocs\logistics\lib\Cake\Model\Validator\CakeValidationRule.php(275): call_user_func_array(Array, Array)
#9 E:\xampp\htdocs\logistics\lib\Cake\Model\Validator\CakeValidationSet.php(135): CakeValidationRule->process('password', Array, Array)
#10 E:\xampp\htdocs\logistics\lib\Cake\Model\ModelValidator.php(267): CakeValidationSet->validate(Array, false)
#11 E:\xampp\htdocs\logistics\lib\Cake\Model\ModelValidator.php(99): ModelValidator->errors(Array)
#12 E:\xampp\htdocs\logistics\lib\Cake\Model\Model.php(3367): ModelValidator->validates(Array)
#13 E:\xampp\htdocs\logistics\lib\Cake\Model\Model.php(1758): Model->validates(Array)
#14 E:\xampp\htdocs\logistics\app\Controller\UsersController.php(79): Model->save(Array)
#15 [internal function]: UsersController->add()
#16 E:\xampp\htdocs\logistics\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#17 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#18 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#19 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#20 {main}
2014-11-29 17:14:11 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'invaliate' at line 1
Request URL: /logistics/users/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\xampp\htdocs\logistics\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('invaliate', Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('invaliate', Array, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Model\Datasource\DboSource.php(609): DboSource->fetchAll('invaliate', Array, Array)
#4 E:\xampp\htdocs\logistics\lib\Cake\Model\Model.php(808): DboSource->query('invaliate', Array, Object(User))
#5 E:\xampp\htdocs\logistics\app\Model\User.php(90): Model->__call('invaliate', Array)
#6 E:\xampp\htdocs\logistics\app\Model\User.php(90): User->invaliate('password_confir...', 'The passwords d...')
#7 [internal function]: User->matchPasswords(Array, Array)
#8 E:\xampp\htdocs\logistics\lib\Cake\Model\Validator\CakeValidationRule.php(275): call_user_func_array(Array, Array)
#9 E:\xampp\htdocs\logistics\lib\Cake\Model\Validator\CakeValidationSet.php(135): CakeValidationRule->process('password', Array, Array)
#10 E:\xampp\htdocs\logistics\lib\Cake\Model\ModelValidator.php(267): CakeValidationSet->validate(Array, false)
#11 E:\xampp\htdocs\logistics\lib\Cake\Model\ModelValidator.php(99): ModelValidator->errors(Array)
#12 E:\xampp\htdocs\logistics\lib\Cake\Model\Model.php(3367): ModelValidator->validates(Array)
#13 E:\xampp\htdocs\logistics\lib\Cake\Model\Model.php(1758): Model->validates(Array)
#14 E:\xampp\htdocs\logistics\app\Controller\UsersController.php(79): Model->save(Array)
#15 [internal function]: UsersController->add()
#16 E:\xampp\htdocs\logistics\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#17 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#18 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#19 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#20 {main}
2014-11-29 17:30:40 Error: Fatal Error (1): Call to a member function link() on a non-object in [E:\xampp\htdocs\logistics\app\Controller\UsersController.php, line 20]
2014-11-29 17:30:40 Error: [FatalErrorException] Call to a member function link() on a non-object
Request URL: /logistics/users/login
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 20)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\xampp\htdocs...', 20, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\xampp\htdocs...', 20, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-29 17:52:52 Error: [NotFoundException] Invalid user
Request URL: /logistics/users/view
Stack Trace:
#0 [internal function]: UsersController->view()
#1 E:\xampp\htdocs\logistics\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#3 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-11-29 17:56:27 Error: Fatal Error (4): syntax error, unexpected T_IF in [E:\xampp\htdocs\logistics\app\Controller\UsersController.php, line 22]
2014-11-29 17:56:27 Error: [FatalErrorException] syntax error, unexpected T_IF
Request URL: /logistics/users/login
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 22)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 22, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\xampp\htdocs...', 22, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-29 17:59:18 Error: Fatal Error (4): syntax error, unexpected ';', expecting ')' in [E:\xampp\htdocs\logistics\app\Controller\AppController.php, line 47]
2014-11-29 17:59:18 Error: [FatalErrorException] syntax error, unexpected ';', expecting ')'
Request URL: /logistics/users/login
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 47)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 47, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\xampp\htdocs...', 47, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-29 17:59:58 Error: Fatal Error (4): syntax error, unexpected ';', expecting ')' in [E:\xampp\htdocs\logistics\app\Controller\AppController.php, line 47]
2014-11-29 17:59:58 Error: [FatalErrorException] syntax error, unexpected ';', expecting ')'
Request URL: /logistics/users/login
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 47)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 47, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\xampp\htdocs...', 47, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-29 18:00:01 Error: Fatal Error (4): syntax error, unexpected ';', expecting ')' in [E:\xampp\htdocs\logistics\app\Controller\AppController.php, line 47]
2014-11-29 18:00:01 Error: [FatalErrorException] syntax error, unexpected ';', expecting ')'
Request URL: /logistics/users/login
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 47)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 47, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\xampp\htdocs...', 47, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-29 18:00:03 Error: Fatal Error (4): syntax error, unexpected ';', expecting ')' in [E:\xampp\htdocs\logistics\app\Controller\AppController.php, line 47]
2014-11-29 18:00:03 Error: [FatalErrorException] syntax error, unexpected ';', expecting ')'
Request URL: /logistics/users/login
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 47)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 47, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\xampp\htdocs...', 47, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-29 18:00:08 Error: Fatal Error (4): syntax error, unexpected ';', expecting ')' in [E:\xampp\htdocs\logistics\app\Controller\AppController.php, line 47]
2014-11-29 18:00:08 Error: [FatalErrorException] syntax error, unexpected ';', expecting ')'
Request URL: /logistics/users/login
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 47)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 47, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\xampp\htdocs...', 47, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-29 18:04:47 Error: Fatal Error (1): Cannot unset string offsets in [E:\xampp\htdocs\logistics\lib\Cake\Controller\Component\AuthComponent.php, line 782]
2014-11-29 18:04:47 Error: [FatalErrorException] Cannot unset string offsets
Request URL: /logistics/users/login
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Cannot unset st...', 'E:\xampp\htdocs...', 782)
#1 [internal function]: ErrorHandler::handleError(1, 'Cannot unset st...', 'E:\xampp\htdocs...', 782, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Cannot unset st...', 'E:\xampp\htdocs...', 782, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-29 18:19:19 Error: Fatal Error (4): syntax error, unexpected ')', expecting ',' or ';' in [E:\xampp\htdocs\logistics\app\Controller\UsersController.php, line 20]
2014-11-29 18:19:19 Error: [FatalErrorException] syntax error, unexpected ')', expecting ',' or ';'
Request URL: /logistics/users/login
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 20)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\xampp\htdocs...', 20, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\xampp\htdocs...', 20, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-29 18:20:33 Error: Fatal Error (1): Class 'SimplePasswordHasher' not found in [E:\xampp\htdocs\logistics\app\Controller\UsersController.php, line 21]
2014-11-29 18:20:33 Error: [FatalErrorException] Class 'SimplePasswordHasher' not found
Request URL: /logistics/users/login
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Class 'SimplePa...', 'E:\xampp\htdocs...', 21)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'SimplePa...', 'E:\xampp\htdocs...', 21, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Class 'SimplePa...', 'E:\xampp\htdocs...', 21, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-29 18:21:30 Error: Fatal Error (1): Class 'SimplePasswordHasher' not found in [E:\xampp\htdocs\logistics\app\Controller\UsersController.php, line 21]
2014-11-29 18:21:30 Error: [FatalErrorException] Class 'SimplePasswordHasher' not found
Request URL: /logistics/users/login
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Class 'SimplePa...', 'E:\xampp\htdocs...', 21)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'SimplePa...', 'E:\xampp\htdocs...', 21, Array)
#2 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Class 'SimplePa...', 'E:\xampp\htdocs...', 21, Array)
#3 E:\xampp\htdocs\logistics\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-29 18:30:02 Error: [MissingControllerException] Controller class LoginController could not be found.
Exception Attributes: array (
  'class' => 'LoginController',
  'plugin' => NULL,
)
Request URL: /logistics/login
Stack Trace:
#0 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-11-29 18:33:39 Error: [MissingActionException] Action UsersController::lo() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'lo',
)
Request URL: /logistics/users/lo
Stack Trace:
#0 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 E:\xampp\htdocs\logistics\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#2 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-11-29 18:46:55 Error: [MissingControllerException] Controller class BranchesController could not be found.
Exception Attributes: array (
  'class' => 'BranchesController',
  'plugin' => NULL,
)
Request URL: /logistics/branches/add
Stack Trace:
#0 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-11-29 18:47:09 Error: [MissingControllerException] Controller class BranchesController could not be found.
Exception Attributes: array (
  'class' => 'BranchesController',
  'plugin' => NULL,
)
Request URL: /logistics/branches
Stack Trace:
#0 E:\xampp\htdocs\logistics\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
